### ISSUE TITLE
Documento HTA

### ISSUE THREAD

**Issue by gpersijn** [Interacao-Humano-Computador/2021.2-Cebraspe#13]
# Descrição:
Criar o documento dde Análise Hierárquica de Tarefas

# Tarefas:
- [x] Criar diagramas
- [x] Criar objetivos
- [x] Criar tabelas

# Critérios de aceitação:
- [x] Git pages atualizado.

**Comment by castroricardo1** [comment]
Issue feita e revisada

**Comment by castroricardo1** [comment]
Issue feita e revisada

**Comment by castroricardo1** [comment]
Issue fechada e revisada.
