### ISSUE TITLE
Metas de Usabilidade

### ISSUE THREAD

**Issue by gpersijn** [Interacao-Humano-Computador/2021.2-Cebraspe#20]
## Descrição:
Documentação das metas da usabilidade

## Tarefas:
- [x] Realizar criação do documento
- [ ] Revisão - @castroricardo1 

## Critérios de aceitação:
- [x] Estar publicado no gitpages.
- [ ]  Documento revisado.

**Comment by castroricardo1** [comment]
Issue revisada
